db.parkingSlots.insertMany([
    {
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },
    {
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": false,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },{
      "userId": null,
      "reserved": true,
      "registered": false,
      "occupied": false,
      "tillTimeUserCanOccupy": null,
    },
  ]);